
import "./globals.css";
import Header from "./_components/Header"
import Footer from "./_components/Footer";
import { CartContextProvider } from "@/app/_context/CartContext";
import { AuthContextProvider } from "@/app/_context/AuthContext";
import Home from "@/app/_components/Home";

export const metadata = {
  title: "Edu-Hub App",
  description: "Generated by create next app",
};

export default function RootLayout({ children}) {
  return (
    <html lang="en">
      <body> 
      <AuthContextProvider>
        <CartContextProvider>       
        <Header />        
        <Home />
        {children}
        <Footer/> 
        </CartContextProvider> 
        </AuthContextProvider>      
        </body>
    </html>
  );
}
