
import "./globals.css";
import Header from "./_components/Header"
import Footer from "./_components/Footer";
import { CartProvider } from "./context/page";
import { AuthContextProvider } from "@/app/context/AuthContext";
import Home from "@/app/_components/Home";

export const metadata = {
  title: "Edu-Hub App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body> 
      <AuthContextProvider>
        <CartProvider>       
        <Header />        
        <Home />
        {children}
        <Footer/> 
        </CartProvider> 
        </AuthContextProvider>      
        </body>
    </html>
  );
}
