const Sdata =[
    {
     id:1,   
     img:"./jonathon.jpg",
     name:"Jonathon Ricks" ,
     course:"Film-Making",
     url:"https://youtu.be/Ow7w7FUAkdk",
     description:"Industry veteran with award-winning experience, offering expert guidance and hands-on training guide students through every aspect of film .",
     review:"Review: 4.2",
     price:"20$", 
    },
    {
     id:2,   
     img:"./abbie.png",
     name:"Abbie Emmons" ,
     course:"Story Writing",
     url:"https://youtu.be/ot3jkbmBKsc",  
     description:"Expert in crafts compelling narratives, sharing insights and techniques honed from successful writing endeavors.",
     review:"Review: 4.5",
     price:"18$", 
    },
    {
     id:3,   
     img:"https://media.istockphoto.com/id/177383755/photo/indian-businessman.jpg?s=2048x2048&w=is&k=20&c=dh6YSpPP9ZRpOjmmGrsNugYj2mpXj4KcuDLYG6sGgPU=",
     name:"Anirudh R" ,
     course:"Cybersecurity",
     url:"https://youtu.be/inWWhr5tnEA",  
     description:"Our cybersecurity specialist offers cutting-edge knowledge, protecting digital assets with industry-tested strategies.",
     review:"Review: 4.7",
     price:"25$", 
    },
    {
     id:4,   
     img:"./angela.jpg",
     name:"Angela Green" ,
     course:"Video-Editing",
     url:"https://www.youtube.com/watch?v=oC3gXr1s_aU&t=8s&pp=ygUfdmlkZW8gZWRpdGluZyBiZWdpbm5lciB0dXRvcmlhbA%3D%3D",   
     description:"Learn video editing from a seasoned professional, mastering techniques used in acclaimed productions and projects ",
     review:"Review: 4.3",
     price:"20$", 
    },
    {
     id:5,   
     img:"./storytelling.jpg",
     name:"Jay Lippman" ,
     course:"Public Speaking",
     url:"https://youtu.be/SIxQPIHtX64",  
     description:"Refine public speaking skills with our communication expert, gaining confidence and eloquence for impactful presentations.",
     review:"Review: 4.2",
     price:"15$", 
    },
    {
     id:6,   
     img:"./gurmeet.jpg",
     name:"Gurmeet Singh" ,
     course:"Backend Development",
     url:"https://youtu.be/PWPtyYoqZCg",     
     description:"Our backend development guru architects robust systems, leveraging advanced technologies for scalable applications.",
     review:"Review: 4.2",
     price:"17$", 
    },
    {
     id:7,   
     img:"./dorothy-jones.jpg",
     name:"Lily Jane" ,
     course:"Frontend Development",
     url:"https://youtu.be/MDLn5-zSQQI", 
     description:"Explore frontend development with our skilled instructor, applying modern web design principles to create engaging interfaces.",
     review:"Review: 4.6",
     price:"14$", 
    },
];
export default Sdata;